server:
   port: 8989

spring:
   application:
      name: API GATWAY
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
         
ribbon: 
  ReadTimeout: 60000 
  connection-timeout: 3000 
  eureka: 
    enabled: true 
            
zuul:
   routes:
      COURSE-SERVICE:
         path: /admin/**
         url: COURSE-SERVICE  
      USER-SERVICE:
         path: /user/**
         url: USER-SERVICE
         

jwt: 
  header: Authorization 
  secret: javainuse 

